config/routes.rb
Rails.application.routes.draw do
  resources :ref_type_fields
  resources :ref_meta
  resources :ref_attributes
  resources :refs
  resources :reftypes

  root 'refs#index'
  get 'bibtexify/' => 'bibtexifies#download'

end

app/controllers/reftypes_controller.rb
class ReftypesController < ApplicationController
  before_action :set_reftype, only: [:show, :edit, :update, :destroy]

  # GET /reftypes
  # GET /reftypes.json
  def index
    @reftypes = Reftype.all
  end

  # GET /reftypes/1
  # GET /reftypes/1.json
  def show
  end

  # GET /reftypes/new
  def new
    @reftype = Reftype.new
  end

  # GET /reftypes/1/edit
  def edit
  end

  # POST /reftypes
  # POST /reftypes.json
  def create
    @reftype = Reftype.new(reftype_params)

    respond_to do |format|
      if @reftype.save
        format.html { redirect_to @reftype, notice: 'Reftype was successfully created.' }
        format.json { render :show, status: :created, location: @reftype }
      else
        format.html { render :new }
        format.json { render json: @reftype.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reftypes/1
  # PATCH/PUT /reftypes/1.json
  def update
    respond_to do |format|
      if @reftype.update(reftype_params)
        format.html { redirect_to @reftype, notice: 'Reftype was successfully updated.' }
        format.json { render :show, status: :ok, location: @reftype }
      else
        format.html { render :edit }
        format.json { render json: @reftype.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reftypes/1
  # DELETE /reftypes/1.json
  def destroy
    @reftype.destroy
    respond_to do |format|
      format.html { redirect_to reftypes_url, notice: 'Reftype was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reftype
      @reftype = Reftype.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reftype_params
      params.require(:reftype).permit(:name)
    end
end

app/helpers/reftypes_helper.rb
module ReftypesHelper
end

app/views/reftypes/_form.html.erb
<%= form_for(@reftype) do |f| %>
  <% if @reftype.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reftype.errors.count, "error") %> prohibited this reftype from being saved:</h2>

      <ul>
      <% @reftype.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reftypes/edit.html.erb
<h1>Editing Reftype</h1>

<%= render 'form' %>

<%= link_to 'Show', @reftype %> |
<%= link_to 'Back', reftypes_path %>

app/views/reftypes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reftypes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reftypes.each do |reftype| %>
      <tr>
        <td><%= reftype.name %></td>
        <td><%= link_to 'Show', reftype %></td>
        <td><%= link_to 'Edit', edit_reftype_path(reftype) %></td>
        <td><%= link_to 'Destroy', reftype, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reftype', new_reftype_path %>

app/views/reftypes/new.html.erb
<h1>New Reftype</h1>

<%= render 'form' %>

<%= link_to 'Back', reftypes_path %>

app/views/reftypes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @reftype.name %>
</p>

<%= link_to 'Edit', edit_reftype_path(@reftype) %> |
<%= link_to 'Back', reftypes_path %>