config/routes.rb
Rails.application.routes.draw do
  resources :ref_type_fields
  resources :ref_meta
  resources :ref_attributes
  resources :refs
  resources :reftypes

  root 'refs#index'
  get 'bibtexify/' => 'bibtexifies#download'

end

app/models/ref_type_field.rb
class RefTypeField < ActiveRecord::Base
  validates :ref_attribute_id, presence: true, uniqueness: {scope: :reftype_id}
  validate :validate_ref_attribute_id
  validates :reftype_id, presence: true
  validate :validate_reftype_id
  validates :obligatory, presence: true
  belongs_to :reftype
  belongs_to :ref_attribute

  def required?
    obligatory == 1
  end
  private
  def validate_reftype_id
    errors.add(:reftype_id, "is invalid") unless Reftype.exists?(self.reftype_id)
  end
  def validate_ref_attribute_id
    errors.add(:ref_attribute_id, "is invalid") unless RefAttribute.exists?(self.ref_attribute_id)
  end
end

app/controllers/ref_type_fields_controller.rb
class RefTypeFieldsController < ApplicationController
  before_action :set_ref_type_field, only: [:show, :edit, :update, :destroy]

  # GET /ref_type_fields
  # GET /ref_type_fields.json
  def index
    @ref_type_fields = RefTypeField.all.order(reftype_id: :asc, obligatory: :desc)
  end

  # GET /ref_type_fields/1
  # GET /ref_type_fields/1.json
  def show
  end

  # GET /ref_type_fields/new
  def new
    @ref_attributes = RefAttribute.all
    @reftypes = Reftype.all
    @ref_type_field = RefTypeField.new
  end

  # GET /ref_type_fields/1/edit
  def edit
    @obs = [{:id => 0, :name => "Valinnainen"}]
    @ref_attributes = RefAttribute.all
    @reftypes = Reftype.all
  end

  # POST /ref_type_fields
  # POST /ref_type_fields.json
  def create
    @ref_type_field = RefTypeField.new(ref_type_field_params)

    respond_to do |format|
      if @ref_type_field.save
        format.html { redirect_to @ref_type_field, notice: 'Ref type field was successfully created.' }
        format.json { render :show, status: :created, location: @ref_type_field }
      else
        @ref_attributes = RefAttribute.all
        @reftypes = Reftype.all
        format.html { render :new }
        format.json { render json: @ref_type_field.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ref_type_fields/1
  # PATCH/PUT /ref_type_fields/1.json
  def update
    respond_to do |format|
      if @ref_type_field.update(ref_type_field_params)
        format.html { redirect_to @ref_type_field, notice: 'Ref type field was successfully updated.' }
        format.json { render :show, status: :ok, location: @ref_type_field }
      else
        format.html { render :edit }
        format.json { render json: @ref_type_field.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ref_type_fields/1
  # DELETE /ref_type_fields/1.json
  def destroy
    @ref_type_field.destroy
    respond_to do |format|
      format.html { redirect_to ref_type_fields_url, notice: 'Ref type field was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ref_type_field
      @ref_type_field = RefTypeField.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ref_type_field_params
      params.require(:ref_type_field).permit(:reftype_id, :ref_attribute_id, :obligatory)
    end
end

app/helpers/ref_type_fields_helper.rb
module RefTypeFieldsHelper
end

app/views/ref_type_fields/_form.html.erb
<%= form_for(@ref_type_field) do |f| %>
  <% if @ref_type_field.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ref_type_field.errors.count, "error") %> prohibited this ref_type_field from being saved:</h2>

      <ul>
      <% @ref_type_field.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :reftype_id %><br>
    <%= f.select :reftype_id, options_from_collection_for_select(@reftypes,:id,:name) %>
  </div>
  <div class="field">
    <%= f.label :ref_attribute_id %><br>
    <%= f.select :ref_attribute_id, options_from_collection_for_select(@ref_attributes,:id,:name) %>
  </div>
  <div class="field">
    <%= f.label :obligatory %><br>
    <select id="ref_type_field_obligatory" name="ref_type_field[obligatory]">
      <option value="0">Valinnainen</option>
      <option value="1" selected>Pakollinen</option>
    </select>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ref_type_fields/edit.html.erb
<h1>Editing Ref Type Field</h1>

<%= render 'form' %>

<%= link_to 'Show', @ref_type_field %> |
<%= link_to 'Back', ref_type_fields_path %>

app/views/ref_type_fields/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ref Type Fields</h1>

<table>
  <thead>
    <tr>
      <th>Tyyppi</th>
      <th>Kenttä</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ref_type_fields.each do |ref_type_field| %>
      <tr>
        <td><%= link_to ref_type_field.reftype.name, ref_type_field %></td>
        <td><%= ref_type_field.ref_attribute.name %></td>
        <td><%= "pakollinen" if ref_type_field.required? %></td>
        <td><%= link_to 'Muokkaa', edit_ref_type_field_path(ref_type_field) %></td>
        <td><%= link_to 'Poista', ref_type_field, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ref type field', new_ref_type_field_path %>

app/views/ref_type_fields/new.html.erb
<h1>New Ref Type Field</h1>

<%= render 'form' %>

<%= link_to 'Back', ref_type_fields_path %>

app/views/ref_type_fields/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Reftype:</strong>
  <%= @ref_type_field.reftype_id %>
</p>

<p>
  <strong>Ref attribute:</strong>
  <%= @ref_type_field.ref_attribute_id %>
</p>

<p>
  <strong>Obligatory:</strong>
  <%= @ref_type_field.obligatory %>
</p>

<%= link_to 'Edit', edit_ref_type_field_path(@ref_type_field) %> |
<%= link_to 'Back', ref_type_fields_path %>