config/routes.rb
Rails.application.routes.draw do
  resources :ref_type_fields
  resources :ref_meta
  resources :ref_attributes
  resources :refs
  resources :reftypes

  root 'refs#index'
  get 'bibtexify/' => 'bibtexifies#download'

end

app/models/ref.rb
class Ref < ActiveRecord::Base
  belongs_to :reftype
  has_many :ref_metum, dependent: :destroy

  validates :reftype_id, presence: true
  validate :validate_reftype_id
  validates :slug, presence: true, uniqueness: true

  def requiredFields?
    requiredIds = reftype.requiredFields.ids - self.ref_metum.pluck(:ref_attribute_id)
    requiredIds.length.zero?
  end
  def to_s
    output = "@#{self.reftype.name}{#{slug},\n"
    self.ref_metum.each do | meta|
      output += meta.to_s
      if meta == self.ref_metum.last
        output += "\n"
      else
        output += ",\n"
      end
    end
    output += "}\n"
    return output
  end
  private
  def validate_reftype_id
    errors.add(:reftype_id, "is invalid") unless Reftype.exists?(self.reftype_id)
  end
end

app/models/reftype.rb
class Reftype < ActiveRecord::Base
   belongs_to :ref
   validates :name , presence: true
   has_many :ref_type_fields, dependent: :destroy
   has_many :ref_attributes, through: :ref_type_fields

  def requiredFields
     ref_attributes.where("obligatory = 1")
  end
   def requiredFieldsIds
     requiredFields.ids
   end
   def hasFields
     not requiredFields.empty?
   end
  def optionalFields
     ref_attributes.where("obligatory = 0")
  end
   def optionalFieldsIds
     optionalFields.ids
   end
end

app/controllers/refs_controller.rb
class RefsController < ApplicationController
  before_action :set_ref, only: [:edit, :update, :destroy]

  # GET /refs
  # GET /refs.json
  def index
    @refs = Ref.all
  end

  # GET /refs/1
  # GET /refs/1.json
  def show
    @ref = Ref.find_by_slug(params[:id])
    respond_to do |format|
      if @ref
        @meta = @ref.ref_metum
        format.html { render :show }
        format.json { render :show, location: @ref, status: :ok }
      else
        format.html { redirect_to refs_path, notice: 'Tuntamaton lyhytnimi' }
        format.json { render json: {}, status: :unprocessable_entity}
      end
    end
  end

  # GET /refs/new
  def new
    @ref = Ref.new
    @ref.reftype_id = Reftype.first.id
    @types = Reftype.all.select {|type| type.hasFields}
  end

  # GET /refs/1/edit
  def edit
    @types = Reftype.all
  end

  # POST /refs
  # POST /refs.json
  def create
    @ref = Ref.new(ref_params)
    @types = Reftype.all
    respond_to do |format|
      if @ref.save
        format.html { redirect_to @ref, notice: 'Ref was successfully created.' }
        format.json { render :show, status: :created, location: @ref }
      else
        @types = Reftype.all
        format.html { render :new }
        format.json { render json: @ref.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /refs/1
  # PATCH/PUT /refs/1.json
  def update
    respond_to do |format|
      if @ref.update(ref_params)
        format.html { redirect_to @ref, notice: 'Ref was successfully updated.' }
        format.json { render :show, status: :ok, location: @ref }
      else
        format.html { render :edit }
        format.json { render json: @ref.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /refs/1
  # DELETE /refs/1.json
  def destroy
    @ref.destroy
    respond_to do |format|
      format.html { redirect_to refs_url, notice: 'Ref was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ref
      @ref = Ref.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def ref_params
      params.require(:ref).permit(:slug, :reftype_id )
    end
end

app/helpers/refs_helper.rb
module RefsHelper
end

app/views/refs/_agform.erb
<script>
  refType = 1;
  optionalFields = [];
  requiredFields = [];

  funQueue = {};
  ref_id =  -1;
  reftype_id = -1;
  slug = "";
  ref_attribute_id = null;
  authenticity_token = null;
  removeFields = function(){
    $("h1").fadeOut();
    $("#createReff").remove()
    reftype_id = $("select[name='ref[reftype_id]']").val();
    slug = $("input[name='ref[slug]']").val()
    var text = $("#ref_reftype_id").find("option:selected").text();
    $("#ref_header").append("<h1>"+slug+"</h1>");
    $("#ref_type").append("<span>"+text+"</span>");
    $("#new_ref").remove()
    $("#ref_send").append("<button id=\"add_ref\">Lisää viite järjestelmään</button>")
    $('#add_ref').click(processFunQueue);
    funQueue["ref"] = {fun:postNewRef,value: function(){ return "moi";},type:reftype_id};

  };
  processFunQueue = function() {
    var keys = Object.keys(funQueue);
    var hasValue = [];
    keys.forEach(function(key){
      if(key != "ref"){
        var value = funQueue[key].value();
        if(value.length > 0) {
          hasValue.push(funQueue[key].type);
        }
      }

    });


    diff = requiredFields.filter(function(x) { return hasValue.indexOf(x) < 0 })
    if(diff == 0){
      if(funQueue["ref"] != undefined){
        var createRef = funQueue["ref"].fun;
        delete funQueue["ref"];
        createRef(processQueue);
      } else {
        processQueue({id: ref_id});
      }
    }else {
      $("#error").append("<p>Muista täyttää pakolliset kentät</p>");
    }

  };

  processQueue = function(data){
    if(ref_id == -1){
      ref_id = data.id;
    }
    var keys = Object.keys(funQueue);
    keys.forEach(function(key){
      var val = funQueue[key].value();
      if(val != ""){
        f = funQueue[key].fun
        delete funQueue[key];
        f(ref_id);

      }
    });
  };
  processAttributeData = function(ref_attribute_id,meta_div_id){
    history.pushState('data', '', '/refs/'+slug); //Huijaa url muistuttamaan show-näkymää
      $.get( '/ref_attributes/'+ref_attribute_id+'.json',
          {}, function(data){
            appendMetaField(ref_attribute_id,data.name,meta_div_id);
          },"json");
  };
  insertAttributeFields = function(){
    requiredFields.forEach(function(ref_attribute_id){
      processAttributeData(ref_attribute_id,"#required");
    });
    optionalFields.forEach(function(ref_attribute_id){
      processAttributeData(ref_attribute_id,"#optional");
    });
  };

  updateAttributeIDs = function(d){
    $.get( '/reftypes/'+refType+'.json',
        {}, function(data){
          optionalFields = data["optionalFieldsIds"];
          requiredFields = data["requiredFieldsIds"];
          insertAttributeFields();
        },"json");
  };

  appendMetaField = function(id,name,meta_div_id){
    div_id = name+id;
    select_name = "s"+name;
    $(meta_div_id).append('<div id=\"'+div_id+'\"></div>');
    $("#"+div_id).append('<select name=\"'+select_name+'\"><option value=\"'+id+'\">'+name+'</option></select>');
    $("#"+div_id).append('<input name=\"value_'+name+'\">');
    //$("#"+div_id).append('<button id=\"b_'+ name+'\" name=\"b_'+name+'\">Lisää '+name+'</button>');

    f = function me(ref_id){
      var params = {ref_metum:{
        ref_id: parseInt(ref_id),
        ref_attribute_id: id,
        value:  $("input[name=value_"+name+"]").val() }
      };
          $.post( '/ref_meta.json',
              params, function(data){
                console.log("ok");
                $("input[name=value_"+name).replaceWith(function () {return $('<span>'+name+'</span>')
                });
              },"json");

    };
    funQueue[name] = {fun:f,value: function(){return $("input[name=value_"+name+"]").val();},type:id}

  };
  postNewRef = function (success){
    $.post( '/refs.json',
        {ref:{
          slug: slug,
          reftype_id: reftype_id
        },
          authenticity_token: authenticity_token
        }, success,"json");
  };
  appendMetaHeaders = function (){
    $("#required").append("<h2>Pakolliset</h2>");
    $("#optional").append("<h2>Valinnaiset</h2>");
  }
  getRefdata = function(){
    var slug = $("input[name='ref[slug]']").val()
    $.get('/refs/'+slug+'.json')
        .fail(function(){
          console.log("Remove fields")
          removeFields();
          console.log("AppendMetaHeaders")
          appendMetaHeaders();
          console.log("updateAttributeIDs")
          updateAttributeIDs();
        });
  }


  $(function() {
    $('#createReff').click(getRefdata);
    authenticity_token = $("input[name='authenticity_token']").val();
    //Suoritetaan JQuery-jutut jos painaa enteriä
    $('#new_ref').on('keyup keypress', function(e) {
      var keyCode = e.keyCode || e.which;
      if (keyCode === 13) {
        e.preventDefault();
        getRefDate();
        return false;
      }
    });
  });
</script>

<section>
<%= form_for(@ref) do |f| %>
    <% if @ref.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@ref.errors.count, "error") %> prohibited this ref from being saved:</h2>

          <ul>
            <% @ref.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label 'Tunniste' %>
      <%= f.text_field :slug %>
    </div>
      <%= f.label 'Tyyppi'%>
      <%= f.select :reftype_id, options_from_collection_for_select(@types,:id,:name) %>
    <div class="actions">

      <% f.submit %>

    </div>

<% end %>
  <button id="createReff" name="commit" value="Luo viite" >Anna viitteelle tunniste ja tyyppi</button>
  <div id="ref">
    <div id="ref_header"></div>
    <div id="ref_type"></div>
    <div id="meta">
      <div id="required"></div>
      <div id="optional"></div>
    </div>
    <div id="ref_send"></div>
    <div id="error"></div>
  </div>

</section>

app/views/refs/_form.html.erb
<%= form_for(@ref) do |f| %>
  <% if @ref.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ref.errors.count, "error") %> prohibited this ref from being saved:</h2>

      <ul>
      <% @ref.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :slug %><br>
    <%= f.text_field :slug %>
  </div>
  <div class="field">
    <%= f.label :reftype_id %><br>
    <%= f.select :reftype_id, options_from_collection_for_select(@types,:id,:name) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/refs/edit.html.erb
<h1>Editing Ref</h1>

<%= render 'form' %>

<%= link_to 'Show', @ref %> |
<%= link_to 'Back', refs_path %>

app/views/refs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Järjestelmässä olevat viitteet</h1>
<h2><%= link_to 'Lataa BibTeX-tiedosto', '/bibtexify' %></h2>
<table>
  <thead>
    <tr>
      <th>Tunnus</th>
      <th>Tyyppi</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @refs.each do |ref| %>
      <tr>
        <td><%= link_to ref.slug ,'refs/'+ref.slug %></td>
        <td><%= ref.reftype.name unless ref.reftype.nil? %></td>
        <td><%= link_to 'Muokkaa', edit_ref_path(ref) %></td>
        <td><%= link_to 'Poista', ref, method: :delete, data: { confirm: 'Oletko varma?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Luo viite', new_ref_path %>

app/views/refs/new.html.erb
<h1>New Ref</h1>

<%= render 'agform' %>

<%= link_to 'Back', refs_path %>

app/views/refs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h1> <%= @ref.slug %></h1>

</p>

<p>
  <strong>Tyyppi:</strong>
  <%= @ref.reftype.name %>
</p>
<h2>Sisältö</h2>
<% @meta.each do |field| %>
    <p><strong> <%= field.ref_attribute.name  %> </strong>: <%= field.value %> <%= link_to 'Edit', edit_ref_metum_path(field) %> |</p>
    <% end %>
<p>
<hr>
  <%= link_to 'Edit', edit_ref_path(@ref) %> |
  <%= link_to 'Back', refs_path %>

</p>