config/routes.rb
Rails.application.routes.draw do
  resources :ref_type_fields
  resources :ref_meta
  resources :ref_attributes
  resources :refs
  resources :reftypes

  root 'refs#index'
  get 'bibtexify/' => 'bibtexifies#download'

end

app/models/ref_attribute.rb
class RefAttribute < ActiveRecord::Base
   has_many :ref_metum, dependent: :destroy
   has_many :ref_type_fields, dependent: :destroy
   validates :name , presence: true
end

app/controllers/ref_attributes_controller.rb
class RefAttributesController < ApplicationController
  before_action :set_ref_attribute, only: [:show, :edit, :update, :destroy]

  # GET /ref_attributes
  # GET /ref_attributes.json
  def index
    @ref_attributes = RefAttribute.all
  end

  # GET /ref_attributes/1
  # GET /ref_attributes/1.json
  def show
  end

  # GET /ref_attributes/new
  def new
    @ref_attribute = RefAttribute.new
  end

  # GET /ref_attributes/1/edit
  def edit
  end

  # POST /ref_attributes
  # POST /ref_attributes.json
  def create
    @ref_attribute = RefAttribute.new(ref_attribute_params)

    respond_to do |format|
      if @ref_attribute.save
        format.html { redirect_to @ref_attribute, notice: 'Ref attribute was successfully created.' }
        format.json { render :show, status: :created, location: @ref_attribute }
      else
        format.html { render :new }
        format.json { render json: @ref_attribute.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ref_attributes/1
  # PATCH/PUT /ref_attributes/1.json
  def update
    respond_to do |format|
      if @ref_attribute.update(ref_attribute_params)
        format.html { redirect_to @ref_attribute, notice: 'Ref attribute was successfully updated.' }
        format.json { render :show, status: :ok, location: @ref_attribute }
      else
        format.html { render :edit }
        format.json { render json: @ref_attribute.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ref_attributes/1
  # DELETE /ref_attributes/1.json
  def destroy
    @ref_attribute.destroy
    respond_to do |format|
      format.html { redirect_to ref_attributes_url, notice: 'Ref attribute was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ref_attribute
      @ref_attribute = RefAttribute.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ref_attribute_params
      params.require(:ref_attribute).permit(:name)
    end
end

app/helpers/ref_attributes_helper.rb
module RefAttributesHelper
end

app/views/ref_attributes/_form.html.erb
<%= form_for(@ref_attribute) do |f| %>
  <% if @ref_attribute.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ref_attribute.errors.count, "error") %> prohibited this ref_attribute from being saved:</h2>

      <ul>
      <% @ref_attribute.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ref_attributes/edit.html.erb
<h1>Editing Ref Attribute</h1>

<%= render 'form' %>

<%= link_to 'Show', @ref_attribute %> |
<%= link_to 'Back', ref_attributes_path %>

app/views/ref_attributes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ref Attributes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ref_attributes.each do |ref_attribute| %>
      <tr>
        <td><%= ref_attribute.name %></td>
        <td><%= link_to 'Show', ref_attribute %></td>
        <td><%= link_to 'Edit', edit_ref_attribute_path(ref_attribute) %></td>
        <td><%= link_to 'Destroy', ref_attribute, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ref attribute', new_ref_attribute_path %>

app/views/ref_attributes/new.html.erb
<h1>New Ref Attribute</h1>

<%= render 'form' %>

<%= link_to 'Back', ref_attributes_path %>

app/views/ref_attributes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ref_attribute.name %>
</p>

<%= link_to 'Edit', edit_ref_attribute_path(@ref_attribute) %> |
<%= link_to 'Back', ref_attributes_path %>